export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_METAMASK_INSTALLED = 'SET_METAMASK_INSTALLED';
export const SET_LOADING_WALLET = 'SET_LOADING_WALLET';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const LOAD_CONTRACTS = 'LOAD_CONTRACTS';